import React from 'react';
import { StyleSheet, ViewStyle, TextStyle } from 'react-native';
import { useTheme } from '@/src/context/ThemeContext';

type StyleCreator = (colors: any) => any;

export const createStyles = (creator: StyleCreator) => {
  return () => {
    const { colors } = useTheme();
    return StyleSheet.create(creator(colors));
  };
};

export const useColors = () => {
  const { colors } = useTheme();
  return colors;
};

export const styles = {
  light: StyleSheet.create({
    container: { flex: 1, backgroundColor: '#FFFFFF' },
    content: { padding: 20, paddingTop: 20 },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
    greeting: { fontSize: 13, color: '#AFAFAF', fontWeight: '900', letterSpacing: 1 },
    titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    titleText: { fontSize: 34, fontWeight: '900', color: '#4B4B4B' },
    settingsButton: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#fff', borderBottomWidth: 5, borderColor: '#F2F2F2', justifyContent: 'center', alignItems: 'center', borderWidth: 2 },
    statsCardContainer: { marginBottom: 24 },
    statsCardShadow: { position: 'absolute', bottom: -6, left: 2, right: 2, top: 10, backgroundColor: '#F2F2F2', borderRadius: 28 },
    statsCard: { backgroundColor: '#FFFFFF', borderRadius: 28, padding: 22, borderWidth: 2, borderColor: '#F2F2F2' },
    levelHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    levelCircle: { width: 66, height: 66, borderRadius: 33, justifyContent: 'center', alignItems: 'center', borderBottomWidth: 5, borderBottomColor: '#CC5500', borderWidth: 3, borderColor: '#fff' },
    levelValue: { color: '#FFFFFF', fontSize: 26, fontWeight: '900' },
    levelInfo: { flex: 1, marginLeft: 16 },
    levelLabel: { color: '#4B4B4B', fontSize: 20, fontWeight: '900' },
    xpText: { color: '#AFAFAF', fontSize: 14, fontWeight: '800', marginTop: 2 },
    coinBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9F9F9', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, gap: 8, borderWidth: 2, borderColor: '#F2F2F2' },
    coinValue: { color: '#FF7F24', fontSize: 20, fontWeight: '900' },
    progressBarWrapper: { marginTop: 4 },
    progressBarContainer: { height: 16, backgroundColor: '#F5F5F5', borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#F2F2F2' },
    progressBar: { height: '100%', backgroundColor: '#00CD00', borderRadius: 8 },
    statsRow: { flexDirection: 'row', gap: 14, marginBottom: 32 },
    miniStat: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 22, padding: 14, alignItems: 'center', gap: 10, borderWidth: 2, borderColor: '#F2F2F2', borderBottomWidth: 6 },
    miniStatIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#F9F9F9', justifyContent: 'center', alignItems: 'center' },
    miniStatValue: { color: '#4B4B4B', fontSize: 17, fontWeight: '900' },
    miniStatLabel: { color: '#AFAFAF', fontSize: 10, fontWeight: '900' },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, marginTop: 10 },
    sectionTitle: { fontSize: 15, fontWeight: '900', color: '#AFAFAF', letterSpacing: 0.5 },
    refreshText: { fontSize: 14, color: '#FF7F24', fontWeight: '900' },
    questList: { gap: 4 },
    modalWrapper: { backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 36, borderTopRightRadius: 36, padding: 26, maxHeight: 600, borderTopWidth: 2, borderColor: '#F2F2F2' },
    modalHandle: { width: 45, height: 6, backgroundColor: '#F2F2F2', borderRadius: 3, alignSelf: 'center', marginBottom: 18 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
    modalHeadTitle: { fontSize: 15, fontWeight: '900', color: '#AFAFAF', letterSpacing: 1 },
    modalQuestTitle: { fontSize: 34, fontWeight: '900', color: '#4B4B4B' },
    modalRewards: { flexDirection: 'row', gap: 14, marginTop: 18, marginBottom: 28 },
    modalRewardItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9F9F9', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, gap: 10, borderWidth: 2, borderColor: '#F2F2F2' },
    modalRewardText: { color: '#4B4B4B', fontWeight: '900', fontSize: 17 },
    bubble: { borderWidth: 2, borderColor: '#F2F2F2', borderRadius: 24, padding: 22, marginBottom: 32, backgroundColor: '#fff' },
    modalDescription: { fontSize: 19, color: '#4B4B4B', lineHeight: 30, fontWeight: '700' },
    proofSection: { backgroundColor: '#F9F9F9', borderRadius: 28, padding: 26, marginBottom: 34, borderWidth: 2, borderColor: '#F2F2F2' },
    proofTitle: { fontSize: 15, fontWeight: '900', color: '#AFAFAF', marginBottom: 18, textAlign: 'center', letterSpacing: 0.5 },
    imageSelectorRow: { flexDirection: 'row', gap: 14 },
    cameraBtn: { flex: 1, height: 110, backgroundColor: '#FFFFFF', borderRadius: 22, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderStyle: 'dashed', borderColor: '#E5E5E5' },
    cameraBtnText: { color: '#FF7F24', fontWeight: '900', fontSize: 13, marginTop: 10 },
    previewContainer: { width: '100%', height: 220, borderRadius: 28, overflow: 'hidden', borderWidth: 2, borderColor: '#F2F2F2' },
    previewImage: { width: '100%', height: '100%', resizeMode: 'cover' },
    removeImgBtn: { position: 'absolute', top: 14, right: 14, backgroundColor: '#FF4B4B', width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: '#fff' },
    successOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', padding: 32, zIndex: 9999 },
    successCard: { width: '100%', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.98)', borderRadius: 40, padding: 36, borderWidth: 3, borderColor: '#F2F2F2' },
    successIconCircle: { width: 140, height: 140, borderRadius: 70, justifyContent: 'center', alignItems: 'center', borderBottomWidth: 8, borderBottomColor: '#CC5500', borderWidth: 4, borderColor: '#fff' },
    successTitle: { fontSize: 36, fontWeight: '900', color: '#4B4B4B', marginTop: 28 },
    successFeedback: { fontSize: 20, color: '#AFAFAF', textAlign: 'center', marginTop: 18, fontWeight: '700', lineHeight: 28 },
    successRewards: { flexDirection: 'row', gap: 40, marginTop: 40 },
    successRewardItem: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F9F9F9', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, borderWidth: 2, borderColor: '#F2F2F2' },
    successRewardValue: { fontSize: 20, fontWeight: '900', color: '#4B4B4B' },
    questButtonsRow: { flexDirection: 'row', gap: 14, marginBottom: 20 },
    questBtn: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 20, padding: 16, alignItems: 'center', borderWidth: 2, borderColor: '#F2F2F2', borderBottomWidth: 6 },
    questBtnAi: { backgroundColor: '#F5E6F8', borderColor: '#9B59B6' },
    questBtnText: { fontSize: 14, fontWeight: '900', color: '#FF7F24', marginTop: 8 },
    questBtnCost: { fontSize: 12, fontWeight: '700', color: '#FF7F24', marginTop: 4 },
    customModalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 24 },
    customModalContent: { backgroundColor: '#FFFFFF', borderRadius: 28, padding: 24, borderWidth: 2, borderColor: '#F2F2F2' },
    customModalTitle: { fontSize: 22, fontWeight: '900', color: '#4B4B4B', textAlign: 'center', marginBottom: 16 },
    customInput: { backgroundColor: '#F9F9F9', borderRadius: 16, padding: 16, fontSize: 16, borderWidth: 2, borderColor: '#F2F2F2', marginBottom: 16, minHeight: 100, textAlignVertical: 'top' },
    customModalButtons: { flexDirection: 'row', gap: 12 },
    customModalBtn: { flex: 1, paddingVertical: 14, borderRadius: 16, alignItems: 'center' },
    customModalBtnCancel: { backgroundColor: '#F2F2F2' },
    customModalBtnConfirm: { backgroundColor: '#9B59B6' },
    customModalBtnText: { fontSize: 16, fontWeight: '900' },
  }),
  dark: StyleSheet.create({
    container: { flex: 1, backgroundColor: '#0F172A' },
    content: { padding: 20, paddingTop: 20 },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
    greeting: { fontSize: 13, color: '#94A3B8', fontWeight: '900', letterSpacing: 1 },
    titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    titleText: { fontSize: 34, fontWeight: '900', color: '#F1F5F9' },
    settingsButton: { width: 56, height: 56, borderRadius: 18, backgroundColor: '#1E293B', borderBottomWidth: 5, borderColor: '#334155', justifyContent: 'center', alignItems: 'center', borderWidth: 2 },
    statsCardContainer: { marginBottom: 24 },
    statsCardShadow: { position: 'absolute', bottom: -6, left: 2, right: 2, top: 10, backgroundColor: '#1E293B', borderRadius: 28 },
    statsCard: { backgroundColor: '#1E293B', borderRadius: 28, padding: 22, borderWidth: 2, borderColor: '#334155' },
    levelHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    levelCircle: { width: 66, height: 66, borderRadius: 33, justifyContent: 'center', alignItems: 'center', borderBottomWidth: 5, borderBottomColor: '#CC5500', borderWidth: 3, borderColor: '#1E293B' },
    levelValue: { color: '#FFFFFF', fontSize: 26, fontWeight: '900' },
    levelInfo: { flex: 1, marginLeft: 16 },
    levelLabel: { color: '#F1F5F9', fontSize: 20, fontWeight: '900' },
    xpText: { color: '#94A3B8', fontSize: 14, fontWeight: '800', marginTop: 2 },
    coinBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#334155', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, gap: 8, borderWidth: 2, borderColor: '#475569' },
    coinValue: { color: '#FF7F24', fontSize: 20, fontWeight: '900' },
    progressBarWrapper: { marginTop: 4 },
    progressBarContainer: { height: 16, backgroundColor: '#334155', borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: '#475569' },
    progressBar: { height: '100%', backgroundColor: '#00CD00', borderRadius: 8 },
    statsRow: { flexDirection: 'row', gap: 14, marginBottom: 32 },
    miniStat: { flex: 1, backgroundColor: '#1E293B', borderRadius: 22, padding: 14, alignItems: 'center', gap: 10, borderWidth: 2, borderColor: '#334155', borderBottomWidth: 6 },
    miniStatIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#334155', justifyContent: 'center', alignItems: 'center' },
    miniStatValue: { color: '#F1F5F9', fontSize: 17, fontWeight: '900' },
    miniStatLabel: { color: '#94A3B8', fontSize: 10, fontWeight: '900' },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, marginTop: 10 },
    sectionTitle: { fontSize: 15, fontWeight: '900', color: '#94A3B8', letterSpacing: 0.5 },
    refreshText: { fontSize: 14, color: '#FF7F24', fontWeight: '900' },
    questList: { gap: 4 },
    modalWrapper: { backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: '#1E293B', borderTopLeftRadius: 36, borderTopRightRadius: 36, padding: 26, maxHeight: 600, borderTopWidth: 2, borderColor: '#334155' },
    modalHandle: { width: 45, height: 6, backgroundColor: '#334155', borderRadius: 3, alignSelf: 'center', marginBottom: 18 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
    modalHeadTitle: { fontSize: 15, fontWeight: '900', color: '#94A3B8', letterSpacing: 1 },
    modalQuestTitle: { fontSize: 34, fontWeight: '900', color: '#F1F5F9' },
    modalRewards: { flexDirection: 'row', gap: 14, marginTop: 18, marginBottom: 28 },
    modalRewardItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#334155', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 18, gap: 10, borderWidth: 2, borderColor: '#475569' },
    modalRewardText: { color: '#F1F5F9', fontWeight: '900', fontSize: 17 },
    bubble: { borderWidth: 2, borderColor: '#334155', borderRadius: 24, padding: 22, marginBottom: 32, backgroundColor: '#1E293B' },
    modalDescription: { fontSize: 19, color: '#F1F5F9', lineHeight: 30, fontWeight: '700' },
    proofSection: { backgroundColor: '#334155', borderRadius: 28, padding: 26, marginBottom: 34, borderWidth: 2, borderColor: '#475569' },
    proofTitle: { fontSize: 15, fontWeight: '900', color: '#94A3B8', marginBottom: 18, textAlign: 'center', letterSpacing: 0.5 },
    imageSelectorRow: { flexDirection: 'row', gap: 14 },
    cameraBtn: { flex: 1, height: 110, backgroundColor: '#1E293B', borderRadius: 22, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderStyle: 'dashed', borderColor: '#475569' },
    cameraBtnText: { color: '#FF7F24', fontWeight: '900', fontSize: 13, marginTop: 10 },
    previewContainer: { width: '100%', height: 220, borderRadius: 28, overflow: 'hidden', borderWidth: 2, borderColor: '#475569' },
    previewImage: { width: '100%', height: '100%', resizeMode: 'cover' },
    removeImgBtn: { position: 'absolute', top: 14, right: 14, backgroundColor: '#FF4B4B', width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', borderWidth: 3, borderColor: '#1E293B' },
    successOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', padding: 32, zIndex: 9999 },
    successCard: { width: '100%', alignItems: 'center', backgroundColor: 'rgba(30,41,59,0.98)', borderRadius: 40, padding: 36, borderWidth: 3, borderColor: '#334155' },
    successIconCircle: { width: 140, height: 140, borderRadius: 70, justifyContent: 'center', alignItems: 'center', borderBottomWidth: 8, borderBottomColor: '#CC5500', borderWidth: 4, borderColor: '#1E293B' },
    successTitle: { fontSize: 36, fontWeight: '900', color: '#F1F5F9', marginTop: 28 },
    successFeedback: { fontSize: 20, color: '#94A3B8', textAlign: 'center', marginTop: 18, fontWeight: '700', lineHeight: 28 },
    successRewards: { flexDirection: 'row', gap: 40, marginTop: 40 },
    successRewardItem: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#334155', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, borderWidth: 2, borderColor: '#475569' },
    successRewardValue: { fontSize: 20, fontWeight: '900', color: '#F1F5F9' },
    questButtonsRow: { flexDirection: 'row', gap: 14, marginBottom: 20 },
    questBtn: { flex: 1, backgroundColor: '#1E293B', borderRadius: 20, padding: 16, alignItems: 'center', borderWidth: 2, borderColor: '#334155', borderBottomWidth: 6 },
    questBtnAi: { backgroundColor: '#2E1065', borderColor: '#A78BFA' },
    questBtnText: { fontSize: 14, fontWeight: '900', color: '#FF7F24', marginTop: 8 },
    questBtnCost: { fontSize: 12, fontWeight: '700', color: '#FF7F24', marginTop: 4 },
    customModalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', padding: 24 },
    customModalContent: { backgroundColor: '#1E293B', borderRadius: 28, padding: 24, borderWidth: 2, borderColor: '#334155' },
    customModalTitle: { fontSize: 22, fontWeight: '900', color: '#F1F5F9', textAlign: 'center', marginBottom: 16 },
    customInput: { backgroundColor: '#334155', borderRadius: 16, padding: 16, fontSize: 16, borderWidth: 2, borderColor: '#475569', marginBottom: 16, minHeight: 100, textAlignVertical: 'top', color: '#F1F5F9' },
    customModalButtons: { flexDirection: 'row', gap: 12 },
    customModalBtn: { flex: 1, paddingVertical: 14, borderRadius: 16, alignItems: 'center' },
    customModalBtnCancel: { backgroundColor: '#334155' },
    customModalBtnConfirm: { backgroundColor: '#A78BFA' },
    customModalBtnText: { fontSize: 16, fontWeight: '900' },
  }),
};